#!/usr/bin/env python

from os import listdir
from re import search, IGNORECASE as i
from platform import system

compiler = 'gfortran'
options = '-O3 -std=f2003 -Wall -pedantic' # -fcheck=all
include = '-llapack -lblas'
executable = 'honeycombinations'

F90 = sorted(file for file in listdir('.') if '.f90' in file)

O = [f90.replace('.f90', '.o') for f90 in F90]

linux = system() == 'Linux'

if linux:
    include = '-L$(LAPACK) -L$(BLAS) ' + include

with open('makefile', 'w') as makefile:
    makefile.write('# generated by makemake.py\n')

    if linux:
        makefile.write('''
LA = /home/jberges/la
LAPACK = $(LA)/lapack-3.5.0
BLAS = $(LA)/BLAS
''')
    
    makefile.write('''
COMPILER = {compiler}
OPTIONS = {options}
INCLUDE = {include}
EXECUTABLE = {executable}

$(EXECUTABLE): {objects}
\t@echo linking $@
\t@$(COMPILER) -o $@ $^ $(INCLUDE)

%.o: %.f90
\t@echo compiling $*
\t@$(COMPILER) $(OPTIONS) -c $<
'''.format(objects=' '.join(O), **vars()))
	
    for f90, o in zip(F90, O):
        makefile.write('\n' + o + ':')
        
        with open(f90) as code:
            for line in code:
                use = search(r'^\s*use\s+(\w+)', line, i)
                if use:
                    makefile.write(' ' + use.group(1) + '.o')
    
    makefile.write('''

cmd = ce=0:0.01:0.2 cX=0.01:0.01:0.2

ARGUMENTS := $(shell python arg.py $(cmd))

.PHONY: clean cleaner jobs $(ARGUMENTS)

clean:
\trm -f *.o *.mod

cleaner: clean
\trm -f $(EXECUTABLE)

jobs: $(ARGUMENTS)

$(ARGUMENTS):
\t./$(EXECUTABLE) $(global) $@
''')
